export enum Trait{
    REGENERATION="REGENERATION",
    ANTI_HEAL="ANTI HEAL",
    SWARM="SWARM",
    AOE="AOE",
    BREAK="BREAK",
    PASSIVE="PASSIVE",
    CATCH="CATCH",
    ROOT="ROOT",
    SLOW="SLOW",
    INVISIBILITY="INVISIBILITY",
    TRUE_SIGHT="TRUE SIGHT",
    BLINKING="BLINKING",
    FAST="FAST"
}


//INVIS VS DETECTION
//BIG REGEN VS REGEN DENY
//IMPORTANT PASSIVES VS BREAK
//FAST VS SLOW
//BLINKING VS ROOT
//CATCH COUNTERS FAST AND BLINKING
//CROWD VS BIG AOE